export const FETCH_START = 'FETCH_START';
export const FETCH_ERROR = 'FETCH_ERROR';
export const BELARUS_RUBLE_RATE_TO_OTHER = 'BELARUS_RUBLE_RATE_TO_OTHER';
export const MENU_OPEN = 'MENU_OPEN';
export const MENU_CLOSE = 'MENU_CLOSE';
export const SET_SHOW_DARK = 'SET_SHOW_DARK';
export const SET_THEME = 'SET_THEME';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
