export const emptyObject = [
  {
    Cur_ID: 440,
    Cur_Abbreviation: 'AUD',
    Cur_Scale: 1,
    Cur_Name: 'Австралийский доллар',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 510,
    Cur_Abbreviation: 'AMD',
    Cur_Scale: 1,
    Cur_Name: 'Армянских драмов',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 441,
    Cur_Abbreviation: 'BGN',
    Cur_Scale: 1,
    Cur_Name: 'Болгарский лев',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 449,
    Cur_Abbreviation: 'UAH',
    Cur_Scale: 100,
    Cur_Name: 'Гривен',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 450,
    Cur_Abbreviation: 'DKK',
    Cur_Scale: 1,
    Cur_Name: 'Датских крон',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 431,
    Cur_Abbreviation: 'USD',
    Cur_Scale: 1,
    Cur_Name: 'Доллар США',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 451,
    Cur_Abbreviation: 'EUR',
    Cur_Scale: 1,
    Cur_Name: 'Евро',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 452,
    Cur_Abbreviation: 'PLN',
    Cur_Scale: 10,
    Cur_Name: 'Злотых',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 508,
    Cur_Abbreviation: 'JPY',
    Cur_Scale: 100,
    Cur_Name: 'Иен',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 461,
    Cur_Abbreviation: 'IRR',
    Cur_Scale: 1,
    Cur_Name: 'Иранских риалов',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 453,
    Cur_Abbreviation: 'ISK',
    Cur_Scale: 1,
    Cur_Name: 'Исландских крон',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 371,
    Cur_Abbreviation: 'CAD',
    Cur_Scale: 1,
    Cur_Name: 'Канадский доллар',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 462,
    Cur_Abbreviation: 'CNY',
    Cur_Scale: 10,
    Cur_Name: 'Китайских юаней',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 394,
    Cur_Abbreviation: 'KWD',
    Cur_Scale: 1,
    Cur_Name: 'Кувейтский динар',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 454,
    Cur_Abbreviation: 'MDL',
    Cur_Scale: 10,
    Cur_Name: 'Молдавских леев',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 448,
    Cur_Abbreviation: 'NZD',
    Cur_Scale: 1,
    Cur_Name: 'Новозеландский доллар',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 455,
    Cur_Abbreviation: 'NOK',
    Cur_Scale: 10,
    Cur_Name: 'Норвежских крон',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 456,
    Cur_Abbreviation: 'RUB',
    Cur_Scale: 100,
    Cur_Name: 'Российских рублей',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 457,
    Cur_Abbreviation: 'XDR',
    Cur_Scale: 1,
    Cur_Name: 'СДР (Специальные права заимствования)',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 421,
    Cur_Abbreviation: 'SGD',
    Cur_Scale: 1,
    Cur_Name: 'Сингапурcкий доллар',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 458,
    Cur_Abbreviation: 'KGS',
    Cur_Scale: 1,
    Cur_Name: 'Сомов',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 459,
    Cur_Abbreviation: 'KZT',
    Cur_Scale: 1,
    Cur_Name: 'Тенге',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 460,
    Cur_Abbreviation: 'TRY',
    Cur_Scale: 1,
    Cur_Name: 'Турецких лир',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 429,
    Cur_Abbreviation: 'GBP',
    Cur_Scale: 1,
    Cur_Name: 'Фунт стерлингов',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 463,
    Cur_Abbreviation: 'CZK',
    Cur_Scale: 100,
    Cur_Name: 'Чешских крон',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 464,
    Cur_Abbreviation: 'SEK',
    Cur_Scale: 10,
    Cur_Name: 'Шведских крон',
    Cur_OfficialRate: 0,
  },
  {
    Cur_ID: 426,
    Cur_Abbreviation: 'CHF',
    Cur_Scale: 10,
    Cur_Name: 'Швейцарский франк',
    Cur_OfficialRate: 0,
  },
];
